recorder:
  reset_time: 1.5
  step_time: 0.8
  rows: 10
  checkpoints: 7
  yaw_steps: 16

  output_path: "../evaluation_data/"
  show_images: False

  motor_control: True
  animation: "walkready"
  play_animation: True
  joint_resolution: 4095

  basler: True
  basler_topic: "image_raw"

  logitech: True
  logitech_source: 0
