# Mandatory parameters
speed_lim_vx: 0.4
speed_lim_vy: 0.15
speed_lim_w: 1.2

accel_lim_vx: 0.3
accel_lim_vy: 0.3
accel_lim_w: 0.1

# Optional parameters
frequency: 20.0
decel_factor: 1.0
decel_factor_safety: 1.0

# Robot velocity feedback type:
#  0 - none
#  1 - odometry
#  2 - end robot commands
robot_feedback: 1
